### ISSUE TITLE
Svelte package

### ISSUE THREAD

**Issue by moritzjacobs** [peerigon/uberschrift#17]
Thanks to an initiative by @TamaraBogantseva we started implementing uberschrift for Svelte @ jscc24 🎉

I pushed the intermediate results to this branch: https://github.com/peerigon/uberschrift/commit/4f70e05326046b95924a733b74a9c21069918c33
The code is working, so we would need to add some finishing touches:

```[tasklist]
### Tasks
- [ ] Discuss the name `svuberschrift` :D
- [ ] Move the .svelte files to a new package
- [ ] Clean out the example project (I strive for minimal reproduction), try and reuse the eslintrc and tsconfig from the @uberschrift/* packages
- [ ] Manage package release and release first version
```

**Comment by moritzjacobs** [comment]
I'm not sure if anyone @peerigon/everyone is firm with Svelte and can assist, maybe @jhnns knows? :)

**Comment by aubcel** [comment]
I know @MartinGassner always wanted to do some svelte, so maybe he's up for it 👀

**Comment by niklashaug** [comment]
I would love to assist but have to see how much time I can spare the next couple of weeks/months

**Comment by MartinGassner** [comment]
I would also like to assist with the development of `svuberschrift`. But I also have to see how much time I can find alongside my other tasks.

**Comment by Narigo** [comment]
We have a very basic implementation of a Svelte version done internally and I used it here as well: https://github.com/Narigo/bayern-tourismus-hackathon-2024/tree/main/src/lib/uberschrift

I thought during the session at JSCC something was created - is that version lost...?

**Comment by moritzjacobs** [comment]
> I thought during the session at JSCC something was created - is that version lost...?

🔝

> I pushed the intermediate results to this branch: https://github.com/peerigon/uberschrift/commit/4f70e05326046b95924a733b74a9c21069918c33
